<?php

namespace Nkg\FormidabBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FieldRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FieldRepository extends EntityRepository
{
  public function getValidFields( \Nkg\FormidabBundle\Entity\Formulaire $form)
  {
    return $this->findBy(array("form"=>$form), array("position"=>"ASC"));
  }
}
